project:
  type: website

website:
  title: "My name is Dulitha"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dulith4
format:
  html:
    theme: sandstone
    css: styles.css



