project:
  type: website
  output-dir: docs

website:
  title: "Not Your Typical Blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dulith4
format:
  html:
    theme: sandstone
    css: styles.css



